# Generated by Django 4.2.4 on 2023-09-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_conversationmessage_is_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationmessage',
            name='is_offer',
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='message_type',
            field=models.CharField(choices=[('message', 'Message'), ('offer', 'Offer')], default='message', max_length=7),
        ),
    ]
