# Generated by Django 4.2.4 on 2023-09-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0003_remove_conversationmessage_is_offer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='is_offer',
            field=models.BooleanField(default=False),
        ),
    ]
