# Generated by Django 4.2.4 on 2023-09-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ebay_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
