# Generated by Django 4.2.4 on 2023-09-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0004_offer_item_item_offers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_offers',
        ),
        migrations.AddField(
            model_name='item',
            name='item_offers',
            field=models.ManyToManyField(blank=True, related_name='items', to='watches.offer'),
        ),
    ]
