# Generated by Django 4.2.4 on 2023-09-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0007_alter_offer_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
