# Generated by Django 4.2.4 on 2023-09-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0009_item_has_box_item_has_papers'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='case_material',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='case_size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='movement',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='water_resistance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
