# Generated by Django 4.2.4 on 2023-09-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0011_remove_item_image_itemimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/'),
        ),
    ]
