# Generated by Django 4.2.4 on 2023-09-28 20:00

import cloudinary.models
import datetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0012_item_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='main_image',
            field=cloudinary.models.CloudinaryField(default=datetime.datetime(2023, 9, 28, 20, 0, 1, 909292, tzinfo=datetime.timezone.utc), max_length=255, verbose_name='main_image'),
            preserve_default=False,
        ),
    ]
